"""Generic prompt builders for the AI pipeline.

These builders are program-agnostic. Each program config calls them with
its own role description, evaluation criteria, tag list, and few-shot examples.

Prompt design principles applied:
 1. Role → Task → Constraints → Format (RTCF structure)
 2. Schema self-documents via Pydantic Field(description=...) — no need to
    repeat field definitions in the prompt text.  The model receives the
    schema via structured-output ``response_format``; the prompt focuses on
    *evaluation criteria* and *grounding rules*.
 3. Few-shot examples are injected per-program, not hardcoded here.
 4. Denoise prompt is fully program-agnostic.
"""

from __future__ import annotations

from typing import List, Optional, Type

from pydantic import BaseModel
from ai_pipeline.programs_config.base.schemas import ReflectionResponse


# ─── Denoise prompt (universal) ──────────────────────────────────────────────

DENOISING_SYSTEM_PROMPT = """
Task: Denoise a Faulty Transcript

You are given a transcript of a phone conversation containing inaccuracies caused by automated transcription errors. Your goal is to reconstruct the original conversation as accurately as possible based on this faulty transcript.

Guidelines:

- Do NOT add or remove any redactions, including:
  - Numbers replaced with asterisks (*)
  - Names replaced with placeholders like #name
  - Any other sensitive or redacted information

- The transcript is imperfect. Carefully interpret and correct it to the best of your ability.

- Provide a cleaned and corrected version of the transcript by editing words and phrasing based on context and your best guess of what was actually spoken.

- Assume the transcript was generated by a low-quality automatic speech recognition system. Your task is to restore the original spoken dialogue as faithfully as possible.

- Important: Only infer what was likely spoken. Do NOT add any new information or details not present in the original audio.

- Output formatting:
  - Clearly label each speaker before their lines (e.g., "Customer", "Agent").
  - Each utterance should be a single line without internal newlines.
  - Separate utterances with a single newline.
  - Example output:
    [
        {"speaker": "Customer", "text": "Hi."},
        {"speaker": "Agent", "text": "Hi, can you please verify your first name for me?"},
        {"speaker": "Customer", "text": "I'm #name. Sorry I have to go. Goodbye."},
    ]
  - Keep the dialogue natural and conversational.
  - Use correct punctuation and capitalization to improve readability.
  - Maintain the original order and flow of the conversation.
"""


# ─── Analysis prompt builder ────────────────────────────────────────────────

def build_analysis_prompt(
    *,
    role: str,
    evaluation_criteria: str,
    tags: List[str],
    few_shot_example: Optional[str] = None,
    analysis_schema: Optional[Type[BaseModel]] = None,
) -> str:
    """Build the per-call analysis system prompt.

    Args:
        role: One-line role identity (e.g. "expert telecom sales coach").
        evaluation_criteria: The full evaluation rubric — what to assess,
            how to score, grounding rules, coaching/sales tip guidance.
            This is the *business logic* of the prompt and is defined
            entirely by the program config.
        tags: Tag vocabulary the model should use for classification.
        few_shot_example: Optional JSON example showing ideal output.
        analysis_schema: The Pydantic model used for structured output.
            Its JSON schema is appended so the model understands field semantics.
    """
    parts = [
        f"You are a {role} analyzing phone call transcripts between agents and customers.",
        "",
        "TASK: Evaluate the transcript and return a structured JSON assessment.",
        "",
        "─── EVALUATION CRITERIA ───",
        evaluation_criteria,
        "",
        "─── TAGGING ───",
        f"Classify the call with 1-3 tags from this list: {tags}",
        "If no tag fits, create one as verb_object (e.g. cancel_plan).",
    ]

    if analysis_schema is not None:
        parts += [
            "",
            "─── OUTPUT SCHEMA ───",
            "Your response MUST conform to this JSON schema. Field descriptions explain what each field means:",
            str(analysis_schema.model_json_schema()),
        ]

    if few_shot_example:
        parts += [
            "",
            "─── EXAMPLE OUTPUT ───",
            few_shot_example,
        ]

    parts += [
        "",
        "Return ONLY a valid JSON object matching the schema. No commentary outside the JSON.",
    ]

    return "\n".join(parts)


# ─── Reflection / summary prompt builder ────────────────────────────────────

def build_reflection_prompt(
    *,
    role: str,
    analysis_context: str,
    coaching_guidelines: str,
    few_shot_example: Optional[str] = None,
    analysis_schema: Optional[Type[BaseModel]] = None,
) -> str:
    """Build the weekly reflection/summary system prompt.

    Args:
        role: Manager/coach role identity.
        analysis_context: Description of what data the model receives
            (field names, KPI names, etc.) — defined by program config.
        coaching_guidelines: Rules for generating coaching tips.
        few_shot_example: Optional example of ideal output.
        analysis_schema: Schema reference so the model understands
            the field definitions in the input data.
    """
    parts = [
        f"You are a {role}.",
        "",
        "TASK: Analyze an agent's recent call data and produce a structured coaching report.",
        "",
        "─── INPUT DATA CONTEXT ───",
        analysis_context,
        "",
        "─── COACHING GUIDELINES ───",
        coaching_guidelines,
        "",
        "─── OUTPUT SCHEMA ───",
        "Your response MUST conform to this JSON schema:",
        str(ReflectionResponse.model_json_schema()),
    ]

    if analysis_schema is not None:
        parts += [
            "",
            "─── INPUT FIELD DEFINITIONS ───",
            "The input data fields are defined by this schema:",
            str(analysis_schema.model_json_schema()),
        ]

    if few_shot_example:
        parts += [
            "",
            "─── EXAMPLE OUTPUT ───",
            few_shot_example,
        ]

    parts += [
        "",
        "Return ONLY valid JSON matching the schema. No commentary outside the JSON.",
    ]

    return "\n".join(parts)
